### PR TITLE
Added 4 New Icons

### PR DESCRIPTION
**Pull request by CreepyCat225**
## Pull Request Checklist:

* [x] Have you added an explanation of which icons you've added and why you'd like us to include them?
* [x] Have you created three versions of each icon across the `svgs`, `appstract-light`, and `appstract-dark` folders?
* [x] Do all three icons have the same name, except for the file type ending? (For example, `app.svg`, `app.png`, and `app.png`)
* [x] Is each file name only comprised of lowercase letters, numbers, and underscores? Underscores should be used only to replace spaces.
    - Acceptable names: `hello.svg`, `bye_bye.svg`, `disney_plus.svg`, `numbers_123.svg`
    - Unacceptable names: `spaces everywhere.svg`, `YouTube.svg`, `$%*&^.svg`
* [x] Have you ensured that all svgs and pngs are 192x192 px with a line width of 6px and a transparent background?
* [x] Did you add activity names for all of your icons to `app/xml/appfilter.xml`?
* [x] Did you add yourself to the `app/xml/contributors.xml` file? :)

## Icons added
Classera
mystc
Vidmate
Microsoft Teams

### Template

For each icon added, please add an entry to the pull request (this text) formatted like this:

* classera (`classera.svg`) - New Icon
```
<item component="ComponentInfo{com.app.classera/com.classera.splash.SplashActivity}" drawable="classera"/>
```
* mystc (`mystc.svg`) - New Icon
```
<item component="ComponentInfo{com.stc/sa.com.stc.ui.landing.SplashScreen}" drawable="mystc"/>
```
* vidmate (`vidmate.svg`) - New Icon
```
<item component="ComponentInfo{com.nemo.vidmate/com.nemo.vidmate.WelcomeActivity}" drawable="vidmate"/>
<item component="ComponentInfo{com.nemo.vidmate/com.nemo.vidmate.host.WelcomeActivity}" drawable="vidmate"/>
```
* microsoft teams (`microsoft_teams.svg`) - New Icon
```
<item component="ComponentInfo{com.microsoft.teams/com.microsoft.skype.teams.Launcher}" drawable="microsoft_teams"/>
<item component="ComponentInfo{com.microsoft.teams/com.microsoft.skype.teams.Launcher}" drawable="teams"/>
```
### Notes
* Only microsoft teams section was already listed in the `appfilter.xml`.

* In the contributers.xml file i added `Microsoft-Teams` don't know if it should be `Microsoft_Teams` or if it'll cause problems.

* Not sure if classera icon fits the theme well so feel free to change anything you don't like about the icons or tell me and i'll change it.
:)

### CODE REVIEW

**Comment by mirrorkeydev** [comment]
Wow, they look great! Thank you!

To your PR and questions, just a couple notes:

- For the microsoft teams entry in `appfilter.xml`, the `drawable=""` thing has to say the name of the file - your second one only says "teams", not "microsoft_teams": 
https://github.com/mirrorkeydev/Appstract/blob/7ef806d0c73755b0a9131c09e4495fa9a50a4db9/app/xml/appfilter.xml#L4733-L4734
- For the contributors.xml file, it doesn't matter how you write `Microsoft Teams`, it's just a regular page that states your contributions :)
- For classera, I think you're right - it's a little busy, and the lines in the middle don't really correspond to anything from the original icon. I scrapped together an alternative you might consider using below:
image

(You can find the .svg [here](https://github.com/mirrorkeydev/mirrorkeydev/blob/master/classera.svg))

It simplifies the original icon by cutting the number of "shards" in half, and makes them softer and more "blobby". The "ring" in the middle shows the round shape of the original. Feel free to use it or modify it, whatever you prefer :)

**Comment by CreepyCat225** [comment]
Hey @mirrorkeydev,

* I know, I looked online and found both so I was a bit confused, but I do think the `microsoft_teams` one is the right one, but really not sure, sorry.

* about the classera icon, I love your design, much cleaner than my cluttered mess, use it instead of mine. I can't update the fork now as I am not near a PC, you can just update the repo yourself with new icon, or I'll do it later, whatever fits you the most.

**Comment by mirrorkeydev** [comment]
Hi @CreepyCat225!
- Oh sorry, let me be more clear: the `drawable=""` contains whatever you named the corresponding file - if you named it `microsoft_teams.png`, it should say `drawable="microsoft_teams"`, if you named it `teams.png` it would just say `drawable="teams"`.
- I'm glad you like it! I'll update the fork if/when I have free time, but it's possible you might get to your computer before that happens :)

**Comment by CreepyCat225** [comment]
Done! 👍

**Pull request merged**
