### PR TITLE
New icon for viu, grab, roborock, galaxy_labs, and adobe_scan!

### PR DESCRIPTION
**Pull request by Artt-ies**
*add files for the 5 new icons
*add myself to contributor list

## Pull Request Checklist:

* [x] Have you added an explanation of which icons you've added and why you'd like us to include them?
* [x] Have you created three versions of each icon across the `svgs`, `appstract-light`, and `appstract-dark` folders?
* [x] Do all three icons have the same name, except for the file type ending? (For example, `app.svg`, `app.png`, and `app.png`)
* [x] Is each file name only comprised of lowercase letters, numbers, and underscores? Underscores should be used only to replace spaces. File names may not begin with a number.
    - Acceptable names: `hello.svg`, `bye_bye.svg`, `disney_plus.svg`, `numbers_123.svg`
    - Unacceptable names: `spaces everywhere.svg`, `YouTube.svg`, `$%*&^.svg`, `dots.between.svg`, `1something.svg`.
* [x] Have you ensured that all svgs and pngs are 192x192 px with a line width of 6px and a transparent background?
* [x] Did you add activity names for all of your icons to `app/xml/appfilter.xml`?
* [x] Did you add yourself to the `app/xml/contributors.xml` file? :)

## Icons added

*viu (`viu.svg`) - New Icon
```
<item component="ComponentInfo{com.viu.phone/com.viu.phone.ui.activity.WelcomeActivity}" drawable="viu"/>

```
*grab (`grab.svg`) - New Icon
```

<item component="ComponentInfo{com.grabtaxi.passenger/com.myteksi.passenger.splash.SplashActivity}" drawable="grab"/>
<item component="ComponentInfo{com.grabtaxi.passenger/com.grab.pax.newface.presentation.newface.NewFace}" drawable="grab"/>

```
*galaxy_labs (`galaxy_labs.svg`) - New Icon
```
<item component="ComponentInfo{com.android.samsung.utilityapp/com.android.samsung.utilityapp.app.presentation.welcomepage.WelcomeActivity}" drawable="galaxy_labs"/>

```
*roborock (`roborock.svg`) - New Icon
```
<item component="ComponentInfo{com.roborock.smart/com.roborock.smart.activity.SplashActivity}" drawable="roborock"/>

```
*adobe_scan(`adobe_scan.svg`) - New Icon
```
<item component="ComponentInfo{com.adobe.scan.android/com.adobe.scan.android.SplashActivity}" drawable="adobe_scan"/>

```

### CODE REVIEW

**Comment by mirrorkeydev** [comment]
Hello @Artt-ies!

Your icons look great, I'd just like to request changes on one of them: `galaxy_lab`. The shapes are too close to each other; on smalls screens the gap will be hard to see and it won't look cohesive with the set. The color choices are really nice! If you can, reducing the number of shapes in `galaxy_lab` would be nice but I understand it can't always be done, depending on the original icon.

**Comment by Artt-ies** [comment]
Hi @mirrorkeydev , I just did a new one with less color and shapes. Do you think separating each shape on the old one or one of the new icons I make fit better? :)

image

image

Thanks in advance

**Comment by mirrorkeydev** [comment]
Oh yes, I like the new ones a lot better! The second one, with the purple circle is my favorite :)

**Comment by Artt-ies** [comment]
> Oh yes, I like the new ones a lot better! The second one, with the purple circle is my favorite :)

Thanks!, I've added the new icon - It should be in there now.

**Comment by mirrorkeydev** [comment]
Looks good, thank you so much for your contribution! :)

**Pull request merged**
