### PR TITLE
multiple icons added

### PR DESCRIPTION
**Pull request by simenopsahl**
## Pull Request Checklist:

* [x] Have you added an explanation of which icons you've added and why you'd like us to include them?
* [x] Have you created three versions of each icon across the `svgs`, `appstract-light`, and `appstract-dark` folders?
* [x] Do all three icons have the same name, except for the file type ending? (For example, `app.svg`, `app.png`, and `app.png`)
* [x] Is each file name only comprised of lowercase letters, numbers, and underscores? Underscores should be used only to replace spaces. File names may not begin with a number.
    - Acceptable names: `hello.svg`, `bye_bye.svg`, `disney_plus.svg`, `numbers_123.svg`
    - Unacceptable names: `spaces everywhere.svg`, `YouTube.svg`, `$%*&^.svg`, `dots.between.svg`, `1something.svg`.
* [x] Have you ensured that all svgs and pngs are 192x192 px with a line width of 6px and a transparent background?
* [x] Did you add activity names for all of your icons to `app/xml/appfilter.xml`?
* [x] Did you add yourself to the `app/xml/contributors.xml` file? :)

## Icons added
* Sleep As Android (`sleep_as_android.svg`) - modified fdroid icon, activity already present in xml
* Plex (`plex.svg`) - modified aptoide icon, activity already present in xml
* Google Chat (`google_chat.svg`) - modified messages icon
```
<!-- google_chat -->
<item component="ComponentInfo{com.google.android.apps.dynamite/com.google.android.apps.dynamite.startup.StartUpActivity}" drawable="google_chat"/>
```
* corona-warn - added a regional app activity to the xml file
```
...
<item component="ComponentInfo{no.fhi.smittestopp_exposure_notification/crc64d475fe8a9f96ce4e.InitializerActivity}" drawable="corona_warn"/>
```
* dominos - added a regional app activity to the xml file
```
...
<item component="ComponentInfo{no.DominosNorway.app/host.exp.exponent.MainActivity}" drawable="dominos"/>
```
* mcdonalds - added a regional app activity to the xml file
```
...
<item component="ComponentInfo{com.mcdonalds.mobileapp/mcdonalds.core.SplashActivity}" drawable="mcdonalds" />
```
* Sim Toolkit (sim_toolkit.svg) - new icon, xml entry already present
* Agenda Widget (agenda_widget.svg) - new icon, xml entry already present
* Your Phone Companion (your_phone_companion.svg) - new icon and xml entry
```
<!-- your_phone_companion -->
	<item component="ComponentInfo{com.microsoft.appmanager/com.microsoft.appmanager.StartUpCoreActivity}" drawable="your_phone_companion"/>
```
* Vipps (vipps.svg + vipps_alt.svg) - made two icons and added an xml entry (mobile payments)
```
<!---vipps_alt-->
	<item component="ComponentInfo{no.dnb.vipps/com.dnb.vipps.ui.activities.SplashActivity}" drawable="vipps_alt" />
```
* Adidas (adidas.svg) - new icon for the Adidas app and added xml entry
```
<!-- adidas -->
	<item component="ComponentInfo{com.adidas.app/com.adidas.intro.IntroActivity}" drawable="adidas"/>
```
* Ruter Billett (ruter_billett.svg) - new icon and xml entry (transit tickets)
```
<!-- ruter_billett -->
	<item component="ComponentInfo{no.ruter.mobile/no.ruter.mobile.activity.SplashActivity}" drawable="ruter_billett"/>
```
* Ruter Reise (ruter_reise.svg) - new icon and xml entry (transit schedules)
```
<!-- ruter_reise -->
	<item component="ComponentInfo{no.ruter.reise/no.ruter.reise.ui.activity.MainActivity}" drawable="ruter_reise"/>
```
* Seriesguide (seriesguide.svg) - new icon, xml entry already present
* Another Widget (another_widget.svg) - new icon and xml entry
```
<!-- another_widget -->
	<item component="ComponentInfo{com.tommasoberlose.anotherwidget/com.tommasoberlose.anotherwidget.ui.activities.MainActivity}" drawable="another_widget"/>
```
* Google Arts & Culture (google_arts_and_culture.svg) - new icon, xml entry already present
* Finn.no (finn_no.svg) - new icon and xml entry (www.finn.no marketplace)
```
<!-- finn_no -->
	<item component="ComponentInfo{no.finn.android/no.finn.android.ui.homepage.HomeActivity}" drawable="finn_no"/>
```
* Klarna (klarna.svg) - new icon and xml entry (payment & invoice)
```
<!-- klarna -->
	<item component="ComponentInfo{com.myklarnamobile/com.myklarnamobile.SplashActivity}" drawable="klarna"/>
```
* Mitt Telenor (telenor.svg) - new icon and xml entry (mobile carrier)
```
<!-- telenor -->
	<item component="ComponentInfo{no.telenor.faktura/no.telenor.faktura.ui.DispatcherActivity}" drawable="telenor"/>
```
* VG (vg.svg + vg_alt.svg) - new icon and xml entry (www.vg.no news)
```
<!-- vg -->
	<item component="ComponentInfo{com.agens.android.vgsnarvei/com.schibsted.publishing.hermes.new_ui.MainActivity}" drawable="vg"/>

<!-- vg_alt -->
	<item component="ComponentInfo{com.agens.android.vgsnarvei/com.schibsted.publishing.hermes.new_ui.MainActivity}" drawable="vg_alt"/>
```
* Cartogram (cartogram.svg) - new icon and xml entry (might need some work)
```
<!-- cartogram -->
	<item component="ComponentInfo{com.round_tower.app.android.wallpaper.cartogram/com.round_tower.cartogram.ui.map.MainActivity}" drawable="cartogram"/>
```
* Discovery+ / DPlay (discovery_plus.svg) - new icon and xml entry (streaming service)
```
<!-- discovery_plus -->
	<item component="ComponentInfo{com.discovery.dplay/com.discovery.app.LaunchActivity}" drawable="discovery_plus"/>
```
* Egg Inc. (egg_inc.svg) - new icon, xml entry already present (game)
* Infinitode (infinitode.svg) - new icon and xml entry (game)
```
<!-- infinitode -->
	<item component="ComponentInfo{com.prineside.tdi/com.prineside.tdi.AndroidLauncher}" drawable="infinitode"/>
```
* Infinitode 2 (infinitode2.svg) - new icon and xml entry (game)
```
<!-- infinitode2 -->
	<item component="ComponentInfo{com.prineside.tdi2/com.prineside.tdi2.AndroidLauncher}" drawable="infinitode2"/>
```
* Kasa Home (kasa_home.svg) - new icon and xml entry (TP Link smart home app)
```
<!-- kasa_home -->
	<item component="ComponentInfo{com.tplink.kasa_android/com.tplink.hellotp.activity.SplashscreenActivity}" drawable="kasa_home"/>
```
* ViaFree (viafree.svg) - new icon and xml entry (streaming service)
```
<!-- viafree -->
	<item component="ComponentInfo{no.viafree.android/com.viafree.android.SplashActivity}" drawable="viafree"/>
```
* ViaPlay (viaplay.svg) - new icon and xml entry (paid version of the above streaming service)
```
<!-- viaplay -->
	<item component="ComponentInfo{com.viaplay.android/com.viaplay.android.vc2.activity.VPSplashScreenActivity}" drawable="viaplay"/>
```
* Coop Medlem (coop_medlem.svg) - new icon and xml entry (Grocery store membership)
```
<!-- coop_medlem -->
	<item component="ComponentInfo{no.coop.members/no.coop.app2020.MainActivity}" drawable="coop_medlem"/>
```
* Danske Bank / Mobilbank (danske_bank_mobilbank.svg) - new icon and xml entry (bank services)
```
<!-- danske_bank_mobilbank -->
	<item component="ComponentInfo{com.danskebank.mobilebank3.no/com.danskebank.mobilebank3.MainActivity}" drawable="danske_bank_mobilbank"/>
```
* EspressoHouse (espresso_house.svg) - new icon and xml entry (coffee shop chain)
```
<!-- espresso_house -->
	<item component="ComponentInfo{com.mobivending.espressohouse/se.espressohouse.app.splash.SplashActivity}" drawable="espresso_house"/>
```
* IKEA (ikea.svg) - new icon and added an xml entry
```
...
<item component="ComponentInfo{com.ingka.ikea.app/com.ingka.ikea.app.splash.SplashActivity}" drawable="ikea"/>
```
* IMDb (imdb.svg) - new icon, xml entry already present
* MENY (meny.svg) - new icon and xml entry (Grocery store)
```
<!-- meny -->
	<item component="ComponentInfo{no.norgesgruppen.apps.meny/no.norgesgruppen.apps.meny.Activities.MainActivity}" drawable="meny"/>
```
* Mr. Porter (mr_porter.svg) - new icon and xml entry (online fashion retail)
```
<!-- mr_porter -->
	<item component="ComponentInfo{com.mrp/com.nap.android.apps.ui.activity.BootstrapActivity}" drawable="mr_porter"/>
```
* PriceSpy / Prisjakt (pricespy_prisjakt.svg) - new icon and xml entry (retail price comparison)
```
<!-- pricespy_prisjakt -->
	<item component="ComponentInfo{se.prisjakt.pricespy/se.prisjakt.pricespy.activity.IndexActivity}" drawable="pricespy_prisjakt"/>
```
* RiksTV (rikstv.svg) - new icon and xml entry (streaming service)
```
<!-- rikstv -->
	<item component="ComponentInfo{no.rikstv.app/no.rikstv.app.MainActivity}" drawable="rikstv"/>
```
* Ruler (ruler.svg) - new icon and xml entry (ruler and measurement app)
```
<!-- ruler -->
	<item component="ComponentInfo{fr.ecp.ruler.app/com.xalphalab.rulerlib.MainActivity}" drawable="ruler"/>
```
* Zalando (zalando.svg) - new icon and xml entry (online fashion retail)
```
<!-- zalando -->
	<item component="ComponentInfo{de.zalando.mobile/de.zalando.mobile.ui.start.SplashActivity}" drawable="zalando"/>
```
* Multy (zyxel_multy.svg) - new icon and xml entry (router management)
```
<!-- zyxel_multy -->
	<item component="ComponentInfo{com.zyxel.multyx/com.zyxel.multyx.SplashActivity}" drawable="zyxel_multy"/>
```
* Android TV Remote (androidtv_remote.svg) - new icon, xml entry already present
* AppSales (app_sales.svg) - new icon and xml entry (play store sales and free promos). Removed from most-requested-icons.txt
```
<!-- app_sales -->
	<item component="ComponentInfo{net.tsapps.appsales/net.tsapps.appsales.ui.main.MainActivity}" drawable="app_sales"/>
```
* Authy (authy.svg) - new icon, xml entry already present
* Gamepad Tester (gamepad_tester.svg) - new icon and xml entry. Might fit other game/controller apps
```
<!-- gamepad_tester -->
	<item component="ComponentInfo{ru.elron.gamepadtester/ru.elron.gamepadtester.ui.main.Main2Activity}" drawable="gamepad_tester"/>
```
* nRF Connect (nrf_connect.svg) - new icon and xml entry (BLE scanner and diagnostics)
```
<!-- nrf_connect -->
	<item component="ComponentInfo{no.nordicsemi.android.mcp/no.nordicsemi.android.mcp.DeviceListActivity}" drawable="nrf_connect"/>
```
* Spectroid (spectroid.svg) - new icon and xml entry (audio spectrum analyzer)
```
<!-- spectroid -->
	<item component="ComponentInfo{org.intoorbit.spectrum/org.intoorbit.spectrum.SpectrumActivity}" drawable="spectroid"/>
```
* Star Walk 2 (star_walk2.svg) - new icon and xml entry (astronomy map)
```
<!-- star_walk2 -->
	<item component="ComponentInfo{com.vitotechnology.StarWalk2Free/com.google.firebase.MessagingUnityPlayerActivity}" drawable="star_walk2"/>
```
* 17Track (17track.svg) - new icon and xml entry (package tracker)
```
<!-- 17track -->
	<item component="ComponentInfo{yqtrack.app/yqtrack.app.ui.splash.SplashActivity}" drawable="17track"/>
```
* AftenPosten (aftenposten.svg) - new icon and xml entry (Norwegian newspaper)
```
<!-- aftenposten -->
	<item component="ComponentInfo{no.cita/com.schibsted.publishing.hermes.new_ui.MainActivity}" drawable="aftenposten"/>
```
* FlightRadar24 (flightradar.svg) - new icon and added an xml entry (flight tracker)
```
...
<item component="ComponentInfo{com.flightradar24free/com.flightradar24free.SplashActivity}" drawable="flightradar"/>
```
* GetWardrobe (getwardrobe.svg) - new icon and xml entry (clothes inventory/wardrobe management)
```
<!-- getwardrobe -->
	<item component="ComponentInfo{com.ThreeBoots/com.ThreeBoots.MainActivity}" drawable="getwardrobe"/>
```
* MobilID (mobil_id_bank_id.svg) - new icon and xml entry (BankID authentication app for Danske Bank, might fit other banks)
```
<!-- mobil-id-bank-id -->
	<item component="ComponentInfo{com.danskebank.mobileid/com.danskebank.mobileid.ui.splash.SplashActivity}" drawable="mobil_id_bank_id"/>
```
* Vy / NSB (vy_nsb.svg & nsb_vy.svg) - 2 new icons and xml entries (Norwegian rail app) old and new icon
```
<!-- vy_nsb -->
	<item component="ComponentInfo{com.intele.nsbmob.app/com.vy.StartupActivity}" drawable="vy_nsb"/>
<!-- nsb_vy -->
	<item component="ComponentInfo{com.intele.nsbmob.app/com.vy.StartupActivity}" drawable="nsb_vy"/>
```
* PornHub / PH Viewer (ph_viewer.svg) - new icon and modified xml entry 😏💦
```
<!-- ph_viewer -->
	<item component="ComponentInfo{com.app.pornhub/com.app.pornhub.alias.normal}" drawable="ph_viewer"/>
	<item component="ComponentInfo{com.app.pornhub/com.app.pornhub.alias.discreet}" drawable="ph_viewer"/>
```
* Fast STL Viewer (stl_viewer.svg) - new icon and xml entry (model/mesh viewer) generic icon, might have other uses
```
<!-- stl_viewer -->
	<item component="ComponentInfo{com.performance.meshview/com.performance.meshview.MeshViewActivity}" drawable="stl_viewer"/>
```
* UE BOOM (ue_boom.svg) - new icon  and added an xml entry
```
...
<item component="ComponentInfo{com.logitech.ueboom/com.logitech.ue.howhigh.activities.SplashActivity}" drawable="ue_boom"/>
```
* BrewFather (brewfather.svg) - new icon and xml entry (homebrewing calculator and recipe app) generic barrel icon might fit other apps
```
<!-- brewfather -->
	<item component="ComponentInfo{com.warpkode.brewfather/com.warpkode.brewfather.MainActivity}" drawable="brewfather"/>
```
* Color Harmony (color_harmony.svg) - new icon and xml entry (color picker and palette app) I noticed there was already an entry for a 'pipette' icon, but no icon file. This icon might fit that.
```
<!-- color_harmony -->
	<item component="ComponentInfo{pl.powsty.colorharmony/pl.powsty.colorharmony.MainActivity}" drawable="color_harmony"/>
```
* ColorLine (color_line.svg) - new icon and xml entry (Cruise onboard services app) this icon could maybe be simplified more
```
<!-- color_line -->
	<item component="ComponentInfo{com.colorline/com.colorline.MainActivity}" drawable="color_line"/>
```
* Frequency Generator (frequency_generator.svg) - new icon and xml entry (sine wave sound generating app) might have other uses
```
<!-- frequency_generator -->
	<item component="ComponentInfo{com.luxdelux.frequencygenerator/com.luxdelux.frequencygenerator.activity.LauncherActivity}" drawable="frequency_generator"/>
```
* Just Eat (just_eat.svg) - alternate icon and xml entry. This was already registered under 'liferando'. I made an alternate icon and an easier to find xml entry, but left the original.
```
...
<item component="ComponentInfo{com.justeat.app.no/com.takeaway.android.activity.Splash}" drawable="liferando"/>
<!-- just_eat -->
	<item component="ComponentInfo{com.justeat.app.no/com.takeaway.android.activity.Splash}" drawable="just_eat"/>
```
* Harmony (logitech_harmony.svg) - new icon, xml entry already present (edited)
```
<!---logitech_harmony-->
	<item component="ComponentInfo{com.logitech.harmonyhub/com.logitech.harmonyhub.ui.SplashActivity}" drawable="logitech_harmony" />
```
* LVR (luisaviaroma.svg) - new icon and xml entry (online fashion retail) very generic icon, probably other uses
```
<!-- luisaviaroma -->
	<item component="ComponentInfo{com.luisaviaroma.luisaviaromaapp_android/com.lvr.MainActivity}" drawable="luisaviaroma"/>
```
* NordNet (nordnet.svg) - new icon and xml entry (Stock and  index fund trading)
```
<!-- nordnet -->
	<item component="ComponentInfo{com.nordnet/com.nordnet.MainActivity}" drawable="nordnet"/>
```
* SD Maid (sd_maid.svg) - I noticed on my phone after makng this that the icon is already present, but not in the github folder. Might be renamed and used as an alternate icon. Or removed.
* Tractive GPS (tractive_gps.svg) - new icon and added an xml entry (Pet tracking app)
```
...
<item component="ComponentInfo{com.tractive.android.gps/com.tractive.android.gps.features.login.GpsAppStartActivity}" drawable="tractive_gps"/>
```
* True Tie (true_tie.svg) - new icon and xml entry (tie knot app) icon probably fits the many other apps like it
```
<!-- true_tie -->
	<item component="ComponentInfo{net.kurdsofts.tieatie/net.kurdsofts.tieatie.SplashActivity}" drawable="true_tie"/>
```
* Trumf (trumf_medlem.svg) - new icon and xml entry (Grocery store chain rewards program) generic 't' icon probably has other uses
```
<!-- trumf_medlem -->
	<item component="ComponentInfo{no.norgesgruppen.apps.trumf.trumf/no.norgesgruppen.apps.trumf.MainActivity}" drawable="trumf_medlem"/>
```
* FolderSync (foldersync.svg) - new icon and xml entry
```
<!-- foldersync -->
	<item component="ComponentInfo{dk.tacit.android.foldersync.full/dk.tacit.android.foldersync.activity.MainActivity}" drawable="foldersync"/>
```
* Microsoft OneDrive (onedrive.svg) - new icon and xml entry. I noticed the xml entry was already added under 'microsoft_one_drive' but with no icon file, left that as is.
```
<!-- onedrive -->
	<item component="ComponentInfo{com.microsoft.skydrive/com.microsoft.skydrive.MainActivity}" drawable="onedrive"/>
```
* Philips Hue (philips_hue.svg) - new icon, fixed xml entry spelling
* Sound Meter (sound_meter.svg) - new icon and xml entry (generic icon, probably fits speed, voltage and other decibel monitor apps)
```
<!-- sound_meter -->
	<item component="ComponentInfo{com.gamebasic.decibel/com.gamebasic.decibel.DecibelActi}" drawable="sound_meter"/>
```
* XZ Closet (xz_closet.svg) - new icon and xml entry (clothes/wardrobe management)
```
<!-- xz_closet -->
	<item component="ComponentInfo{fashion.style.coordinate.app.xz/com.tns.NativeScriptActivity}" drawable="xz_closet"/>
```
*  BLOB LWP (blob_lwp.svg) - new icon and xml entry
```
<!-- blob_lwp -->
	<item component="ComponentInfo{com.maxelus.livewallpaper.blob/com.maxelus.libpref.MaxelusLuncherActivity}" drawable="blob_lwp"/>
```
* Bubbles LWP (bubbles_lwp.svg) - new icon and xml entry
```
<!-- bubbles_lwp -->
	<item component="ComponentInfo{cdev.bubbles/cdev.bubbles.MySettingsActivity}" drawable="bubbles_lwp"/>
```
* Clas Ohlson (clas_ohlson.svg) - new icon and xml entry (Scandinavian hardware store)
```
<!-- clas_ohlson -->
	<item component="ComponentInfo{com.clasohlson.app/com.clasohlson.app.MainActivity}" drawable="clas_ohlson"/>
```
* Google Home (google_home.svg) - new icon and xml entry. Found an entry under 'chromecast' but no icon, left as is.
```
<!-- google_home -->
	<item component="ComponentInfo{com.google.android.apps.chromecast.app/com.google.android.apps.chromecast.app.DiscoveryActivity}" drawable="google_home"/>
```
* Imgur (imgur.svg) - new icon, xml entry already present
* MyAnimeList (mal_my_anime_list.svg) - new icon and added more xml entries
```
...
<item component="ComponentInfo{com.drutol.malclient/crc64538156a8cca88d64.MainActivity}" drawable="pocket_mal"/>
	<item component="ComponentInfo{net.myanimelist.app/net.myanimelist.presentation.activity.HomeActivity}" drawable="pocket_mal"/>

	<!-- mal_my_anime_list -->
	<item component="ComponentInfo{com.g.pocketmal/com.g.pocketmal.ui.SplashActivity}" drawable="mal_my_anime_list" />
	<item component="ComponentInfo{com.drutol.malclient/crc64538156a8cca88d64.MainActivity}" drawable="mal_my_anime_list"/>
	<item component="ComponentInfo{net.myanimelist.app/net.myanimelist.presentation.activity.HomeActivity}" drawable="mal_my_anime_list"/>
```
* Xiaomi Mi Fit (mi_fit.svg) - new icon, xml entry already present
* Norstat Panel (norstat_panel.svg) - new icon and xml entry. Generic 'N' icon, could have other uses.
```
<!-- norstat_panel -->
	<item component="ComponentInfo{no.norstat.panelapp/crc6488dbf9ed225ce582.SplashActivity}" drawable="norstat_panel"/>
```
* NRK (nrk.svg) - new icon and xml entry (Norwegian state broadcaster news)
```
<!-- nrk -->
	<item component="ComponentInfo{no.nrk.mobil.app/no.nrk.mobil.app.activity.SplashScreenActivity}" drawable="nrk"/>
```
* NRK Radio (nrk_radio.svg) - new icon and xml entry (Norwegian state broadcaster radio)
```
<!-- nrk_radio -->
	<item component="ComponentInfo{no.nrk.mobil.radio/no.nrk.mobil.radio.MainActivity}" drawable="nrk_radio"/>
```
* NRK TV (nrk_tv.svg) - new icon and xml entry (Norwegian state broadcaster TV)
```
<!-- nrk_tv -->
	<item component="ComponentInfo{no.nrk.tv/no.nrk.tv.view.MobileSplashScreenActivity}" drawable="nrk_tv"/>
```
* PatientSky (patient_sky.svg) - new icon and xml entry (healthcare service)
```
<!-- patient_sky -->
	<item component="ComponentInfo{com.patientsky.patientsky/com.patientsky.patientsky.MainActivity}" drawable="patient_sky"/>
```
* Elder Scrolls Blades (tes_blades.svg) - new icon and xml entry (game)
```
<!-- tes_blades -->
	<item component="ComponentInfo{com.bethsoft.blade/com.bethesda-player.BgsPlayerActivity}" drawable="tes_blades"/>
```
* Boozt (boozt.svg) - new icon and xml entry (online clothes retail)
```
<!-- boozt -->
	<item component="ComponentInfo{com.boozt/com.boozt.ui.BooztActivity}" drawable="boozt"/>
```
* Booztlet /booztlet.svg) - new icon and xml entry (same as above, but outlet)
```
<!-- booztlet -->
	<item component="ComponentInfo{com.booztlet/com.booztlet.ui.SplashActivity}" drawable="booztlet"/>
```
* Pixel Dungeon (pixel_dungeon.svg) - new icon and added xml entry for Shattered Pixel Dungeon
```
	<item component="ComponentInfo{com.shatteredpixel.shatteredpixeldungeon/com.shatteredpixel.shatteredpixeldungeon.android.AndroidLauncher}" drawable="pixel_dungeon"/>
```
* Digipost (posten_digipost.svg) - new icon and xml entry (Norwegian Mail secure documents and receipts storage)
```
<!-- posten_digipost -->
	<item component="ComponentInfo{no.digipost.android/no.digipost.android.MainActivity}" drawable="posten_digipost"/>
```
* RunPee (run_pee.svg) - new icon and xml entry (app for cinemagoers, vibrates/notifies for opportune times to go to the toilet)
```
<!-- run_pee -->
	<item component="ComponentInfo{air.RunPee/air.RunPee.MainActivity}" drawable="run_pee"/>
```
* Sony Cinema Pro (sony_cinema_pro.svg) - new icon and xml entry (advanced version of stock Sony camera app)
```
<!-- sony_cinema_pro -->
	<item component="ComponentInfo{com.sonymobile.cinemapro/com.sonymobile.cinemapro.CinemaProActivity}" drawable="sony_cinema_pro"/>
```
* Sony Photo Pro (sony_photo_pro.svg) - new icon and xml entry (same as above, photo version)
```
<!-- sony_photo_pro -->
	<item component="ComponentInfo{com.sonymobile.photopro/com.sonymobile.photopro.PhotoProActivity}" drawable="sony_photo_pro"/>
```
* Tripadvisor (tripadvisor.svg) - new icon and added an xml entry to <!---tripadvisor-->
```
<item component="ComponentInfo{com.tripadvisor.tripadvisor/com.tripadvisor.android.ui.launcher.LauncherActivity}" drawable="tripadvisor"/>

### CODE REVIEW

**Comment by simenopsahl** [comment]
there are some more icons i am working on, will add over the coming days

**Comment by mirrorkeydev** [comment]
Hello @simenopsahl!

Thank you so much for your contribution!

Please be aware that I am unable to review or merge PRs until September 4th, 2021 due to my summer employment terms. Please see the [README ](https://github.com/mirrorkeydev/Appstract#readme) for more details.

My release schedule remains the same because I release about every 3 months anyway, so the icons will not be in Appstract any later than usual, it's just that the review + merge is pushed back to right before I release.

Thanks for your patience and understanding :) In the meantime, please feel free to continue adding/updating items in this PR.

**Comment by yangchoo** [comment]
@mirrorkeydev Hope your summer employment went well!

Any chance you could review this PR and incorporate it as part of the next release? There's a whole bunch of icons here which I'll love to have present in the icon pack :) 

In particular, icons for Google apps such as `Google Home` and `Google  Chat` would be awesome.

**Comment by mirrorkeydev** [comment]
Great job with these @simenopsahl, they look great! I'll merge them in and cut a new release of Appstract as soon as https://github.com/simenopsahl/Appstract/pull/1 is merged (or you add the rename changes manually, up to you). I wouldn't normally be so strict about naming conventions but the app won't compile if the naming convention of the dashboard isn't upheld.

Again, thank you for your patience.

**Pull request merged**
