### PR TITLE
Suggestion for 2 icons

### PR DESCRIPTION
**Pull request by JakobST1n**
## Pull Request Checklist:

* [X] Have you added an explanation of which icons you've added and why you'd like us to include them?
* [X] Have you created three versions of each icon across the `svgs`, `appstract-light`, and `appstract-dark` folders?
* [X] Do all three icons have the same name, except for the file type ending? (For example, `app.svg`, `app.png`, and `app.png`)
* [X] Is each file name only comprised of lowercase letters, numbers, and underscores? Underscores should be used only to replace spaces. File names may not begin with a number.
    - Acceptable names: `hello.svg`, `bye_bye.svg`, `disney_plus.svg`, `numbers_123.svg`
    - Unacceptable names: `spaces everywhere.svg`, `YouTube.svg`, `$%*&^.svg`, `dots.between.svg`, `1something.svg`.
* [X] Have you ensured that all svgs and pngs are 192x192 px with a line width of 6px and a transparent background?
* [x] Did you add activity names for all of your icons to `app/xml/appfilter.xml`?
* [X] Did you add yourself to the `app/xml/contributors.xml` file? :)

## Icons added
* Hjelp 113 (`hjelp_113.svg`) - New icon
I gave it a shot, not completly sure. But I tried to keep the colors in the original icon and add 113 as that is obviously the most important recognizable factor with the original. 
I am a little bit unsure of this, as it seemed a bit weird, but `com.favouritesystems.android.emergencyapp.nla113crc64af550863d7fdfc02.MainActivity` is the thing that comes up when using the `Package Names` app.
```
<item component="ComponentInfo{com.favouritesystems.android.emergencyapp/com.favouritesystems.android.emergencyapp.nla113crc64af550863d7fdfc02.MainActivity}" drawable="hjelp_113"/>
```
* Wolfram alpha (`wolfram_alpha.svg`) - New icon?
It is in appfilter.xml but I can't find the drawable for it, so here is a suggestion for that icon.
When opening the svg in preview there is a small gap between all of the shapes of the background, but they shouldn't really be there. They do not show up in illustrator at least, and when exporting to png with "Art optimized" anti-aliasing they do not appear. So I don't know why they appear there...

I have been enjoying this icon pack very much, and thought it would be fun to give it a shot. I can open a PR for either of the icons if you want, include them if you want :P

### CODE REVIEW

**Comment by mirrorkeydev** [comment]
Hello @JakobST1n!

I'm sorry about the delay in getting back to you on this PR. It's midterm week and my professors felt it was appropriate to put multiple giant projects and midterms all in the same week 😔 

Anyway, I took a look at your icons, and here is my feedback!

## wolfram alpha
This looks great! The only thing is that per the [style guide](https://github.com/mirrorkeydev/Appstract/blob/master/CONTRIBUTING.md), having multiple colors touching in one "shape" goes against the design ethos of Appstract. So the only change I would request would be to remove one of the colors so it's a completely 'flat' shape, kind of like the tab icon for :)
image

## hjelp113
This looks good as well! I especially like the shape of the `3` that you made. However, I would challenge you to either choose the three colors of the original _or_ the three numbers of the original -- having both makes the icon look a little cluttered, especially once it's on small phone screens. If it were me, I would probably choose the three numbers, since I assume `113` is the emergency line in your country, and then use yellow as the background, since it's the dominant color. You could get creative with the shape of the yellow blob in the background; looking at the original app, there's a lot of little shapes that you can steal:
image
the "snake" seal from the middle (my personal favorite, since it's so recognizable as "emergency" or "ambulance":
image
or the specific "circle with wings" shape they've got going on:
image


Let me know if you have any other questions :)

Best,
Melanie

**Comment by JakobST1n** [comment]
I have far too much to do currently, so I haven't had the time to look at this. The wolfram-icon is pretty straight forward though. While removing the accent colours, I wondered wether it maybe became a bit boring. So I made a example with the lines a bit offset. Do you think that is better or should the lines be in the center?
Screenshot 2021-03-02 at 16 43 49

**Comment by mirrorkeydev** [comment]
No worries, I completely get it (I'm about half a month behind on my release schedule for Appstract because classes and work have me swamped). 

Personally, I like the centered version of the wolfram icon better :)

**Comment by mirrorkeydev** [comment]
Closing due to inactivity, feel free to reopen if you ever return to this :)

**Pull request closed without merging**
