### PR TITLE
Add 6 icons

### PR DESCRIPTION
**Pull request by ewen-lbh**
Hi! I'm the guy that emailed you some icon ideas (and made a [reddit post about it](https://www.reddit.com/r/NovaLauncher/comments/bk5o33/remove_if_its_too_off_topic_some_icons_i_designed/)) about a year ago, so nice to see this pack become open to contributions on Github! :)

I'm here to contribute again for some icons that appear on my home screen but aren't "appstracted" yet!

## Pull Request Checklist:

* [x] Have you added an explanation of which icons you've added and why you'd like us to include them?
* [x] Have you created three versions of each icon across the `svgs`, `appstract-light`, and `appstract-dark` folders?
* [x] Do all three icons have the same name, except for the file type ending? (For example, `app.svg`, `app.png`, and `app.png`)
* [x] Is each file name only comprised of lowercase letters, numbers, and underscores? Underscores should be used only to replace spaces. File names may not begin with a number.
    - Acceptable names: `hello.svg`, `bye_bye.svg`, `disney_plus.svg`, `numbers_123.svg`
    - Unacceptable names: `spaces everywhere.svg`, `YouTube.svg`, `$%*&^.svg`, `dots.between.svg`, `1something.svg`.
* [x] Have you ensured that all svgs and pngs are 192x192 px with a line width of 6px and a transparent background?
* [x] Did you add activity names for all of your icons to `app/xml/appfilter.xml`?
* [x] Did you add yourself to the `app/xml/contributors.xml` file? :)

## Icons added

- [Firefox Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix)
- [liO Occitanie](https://play.google.com/store/apps/details?id=fr.airweb.occitanie) The app to commute by bus in the south of France
- [OUI.sncf](https://play.google.com/store/apps/details?id=com.vsct.vsc.mobile.horaireetresa.android) The app to buy train tickets in France
- [Société Générale](https://play.google.com/store/apps/details?id=mobi.societegenerale.mobile.lappli) A french bank's app
- [RocketBook](https://play.google.com/store/apps/details?id=com.rb.rocketbook) Used to scan pages of RocketBook's smart notebooks (and whiteboards)
- [Tachiyomi](https://f-droid.org/en/packages/eu.kanade.tachiyomi/) A FOSS manga reader

Tachiyomi has [multiple forks](https://tachiyomi.org/forks/) which should get the same icon, I only added one of those forks (J2K) to `applist.xml`, I'll add the others too

### Template

For each icon added, please add an entry to the pull request (this text) formatted like this:

* Firefox Nightly (`firefox_nightly.svg`) - New Icon
```
<item component="ComponentInfo{org.mozilla.fenix/org.mozilla.fenix.App}" drawable="firefox_nightly" />
```

* Tachiyomi (`tachiyomi.svg`) - New Icon
```
<item component="ComponentInfo{eu.kanade.tachiyomi/eu.kanade.tachiyomi.ui.main.MainActivity}" drawable="tachiyomi"/>
<item component="ComponentInfo{eu.kanade.tachiyomi.dev/eu.kanade.tachiyomi.ui.main.MainActivity}" drawable="tachiyomi"/>
```

* OUI.sncf (`oui_sncf.svg`) - New Icon
```
<item component="ComponentInfo{com.vsct.vsc.mobile.horaireetresa.android/com.vsct.vsc.mobile.horaireetresa.android.activity.SplashActivity}" drawable="oui_sncf"/>
```

* Société Générale (`societe_generale.svg`) - New Icon
```
<item component="ComponentInfo{mobi.societegenerale.mobile.lappli/mobi.societegenerale.mobile.lappli.react.MainActivity}" drawable="societe_generale" />
```

* Lio Occitanie (`lio_occitanie.svg`) - New Icon
```
<item component="ComponentInfo{fr.airweb.occitanie/fr.airweb.catp.ui.splash.SplashActivity" drawable="lio_occitanie"/>
```

* RocketBook (`rocketbook.svg`) - New Icon
```
<item component="ComponentInfo{com.rb.rocketbook/com.rb.rocketbook.StartupActivity}" drawable="rocketbook" />
```

~~I have some issues with how Illustrator exports to SVG, when I opened Firefox Focus' .svg file to create the Nightly variant, I saw two artboards, one with the original icon as an image, and another with the appstract icon. When I open the very same file in a web browser, it just shows me the appstract icon. I don't know how you did that, when I open .svg files I created (with two artboards just like Firefox Focus' .svg) in a web browser, it cuts weirdly and shows the image too...~~

~~Is it okay if I leave only the appstract icon in the .svg file (one artboard)?~~

EDIT: Github's rich preview shows the correct SVG (only the appstract icon), so I _guess_ it's okay?

### CODE REVIEW

**Comment by mirrorkeydev** [comment]
Hello @ewen-lbh!

It's nice to see you again!

### First, to your question:
So I use Inkscape to create my icons, and Inkscape only allows a single "artboard" (called a document). What you're seeing is that I used to put the reference image for an icon outside of the document, and relied on the fact that Inkscape will construct an .SVG such that only items inside of the document are visible.
image
This isn't required of you by any means, so it's perfectly fine to just leave just the Appstract icon in the file :)

### Second, some review on your PR:
It looks like for the contributors file, you forgot the closing tag for your entry (`/>`). I'm not actually sure what the dashboard will do if you don't include an image or a link for a contributor, so we'll have to see when I test deploy the new changes if I need to add some placeholder links.

Additionally, you've got 22 icons listed, which is pretty long and might not look good on mobile - my rule of thumb is that if you're exceeding 20-30 icons, you might consider writing "22 icons" or maybe "22 icons, including [top 3 favorites that you made]".

I'm not sure if you had a chance to look at the design ethos in [`contributing.md`](https://github.com/mirrorkeydev/Appstract/blob/master/CONTRIBUTING.md), but I noticed some parts of one of your designs that conflicted.

image

Firstly, `tachiyomi.png`: I'm not sure if this was intentional, but one of the colored blobs is on top of the black lines, which isn't a pattern historically used in Appstract. Additionally, you've chosen to represent the kanji with colored blobs, and the background circle with a circle outline, which has the result of creating lots of small colored blobs; these can look very busy when viewed at a small screen size, and don't really mesh with the rest of Appstract, which tries to promote large singular (where possible) background blobs with some lines on top of them to represent the icon's design. For example, here is how it would look if we flipped the kanji and circle:
image
(.svg [here](https://github.com/mirrorkeydev/mirrorkeydev/blob/master/tachiyomi.svg))

You don't have to use my redesign (although you're certainly welcome to), I just wanted to provide it as an example of some differences between the icon and the design ethos of the other icons.

Great job on the rest of the icons, though! They look great, and I'm very excited to have your contributions added to Appstract :)

**Comment by ewen-lbh** [comment]
>  I'm not actually sure what the dashboard will do if you don't include an image or a link for a contributor, so we'll have to see when I test deploy the new changes if I need to add some placeholder links.

Yeah I just forgot to finish filling out my entry… (i might need more sleep)

> Additionally, you've got 22 icons listed, which is pretty long and might not look good on mobile - my rule of thumb is that if you're exceeding 20-30 icons, you might consider writing "22 icons" or maybe "22 icons, including [top 3 favorites that you made]".

Wasn't exactly sure what to do about this, but yeah let's go with "22, including <top 3>". I'll update that too

> Firstly, tachiyomi.png (...)

I also thought about inverting the whole thing (just like your redesign does), and I'll gladly use your redesign! I'll just change the curvature on the smaller vertical line to the left.

> First, to your question: (...)

Yeah like I said in my EDIT, it seems like github renders the .svg files as expected, but I'll get rid of the references (or at least move them out of the artboard) so that it won't mess up anywhere.

Not related, but I found an app to get the package name and main activity name, it's called [Package Name Viewer](https://play.google.com/store/apps/details?id=com.csdroid.pkg&hl=en_US&gl=US), you might want to add this to the contributing guide (the obscure "lio occitanie" app shown no results when searching for an appfilter.xml entry)

I'm pretty busy w/ studies too, so I'll try making comitting those changes, I think you can expect updates before xmas

**Comment by mirrorkeydev** [comment]
Oh forgot to do this yesterday: I'm gonna move this into a draft state until you're ready to have me look at it again :)

**Comment by ewen-lbh** [comment]
I've updated tachiyomi's icon, I'm re-marking the PR as "Ready for review"

**Comment by mirrorkeydev** [comment]
Looks good, I'll merge it in! Thanks for contributing :)

**Pull request merged**
