### PR TITLE
Ghost

### PR DESCRIPTION
**Pull request by The-King-Slayer**
## Pull Request Checklist:

* [x] Have you added an explanation of which icons you've added and why you'd like us to include them?
* [x] Have you created three versions of each icon across the `svgs`, `appstract-light`, and `appstract-dark` folders?
* [x] Do all three icons have the same name, except for the file type ending? (For example, `app.svg`, `app.png`, and `app.png`)
* [x] Is each file name only comprised of lowercase letters, numbers, and underscores? Underscores should be used only to replace spaces. File names may not begin with a number.
    - Acceptable names: `hello.svg`, `bye_bye.svg`, `disney_plus.svg`, `numbers_123.svg`
    - Unacceptable names: `spaces everywhere.svg`, `YouTube.svg`, `$%*&^.svg`, `dots.between.svg`, `1something.svg`.
* [x] Have you ensured that all svgs and pngs are 192x192 px with a line width of 6px and a transparent background?
* [x] Did you add activity names for all of your icons to `app/xml/appfilter.xml`?
* [x] Did you add yourself to the `app/xml/contributors.xml` file? :)

### Template

For each icon added, please add an entry to the pull request (this text) formatted like this:

* App Name (`app_name.svg`) - [New/Redesigned] Icon
```
<item component="ComponentInfo{Activity Name 1}" drawable="app_name"/>
<item component="ComponentInfo{Activity Name 2}" drawable="app_name"/>
```

###### Gotchas:
- The name inside `drawable=` must match the name of the file (For example, `orange.svg` would have `drawable="orange"`)
- For help finding/adding activity names, please see the [Contributing Guide](https://github.com/mirrorkeydev/Appstract/blob/master/CONTRIBUTING.md#activity-names)

### Examples (delete before opening PR)

* Camera (`camera.svg`) - Redesigned Icon
```
<item component="ComponentInfo{com.android.camera/com.android.camera.view.CameraActivity}" drawable="camera"/>
<item component="ComponentInfo{com.mediatek.camera/com.mediatek.camera.CameraLauncher}" drawable="camera"/>
<item component="ComponentInfo{com.GoogleCamera.Wichaya/com.android.camera.CameraLauncher}" drawable="camera"/>
<item component="ComponentInfo{com.hmdglobal.app.camera/com.hmdglobal.app.camera.GuideActivity}" drawable="camera"/>
```

* Poshmark (`poshmark.svg`) - New Icon
```
<item component="ComponentInfo{com.poshmark.app/com.poshmark.ui.MainActivity}" drawable="poshmark"/>
```

* Disney+ (`disney_plus.svg`) - New Icon 
```
<item component="ComponentInfo{com.disney.disneyplus/com.bamtechmedia.dominguez.main.MainActivity}" drawable="disney_plus"/>
<item component="ComponentInfo{jp.co.disney.apps.gm.disneyvod/com.ascendon.disney.activity.DJLoaderActivity}" drawable="disney_plus"/>
```

### CODE REVIEW

**Comment by The-King-Slayer** [comment]
Hi @mirrorkeydev ,

First of all belated Happy New Year XD

So, here are the new icons as I promised. Thanks a ton, your advice worked wonders. ("Be SIMPLER than you think you need to be" It made me improve my thinking :)
I have tried my best to stick to the ethos still if any changes are reqd, please let me know.

Have a great one, cheers :)

Here's the change_log:

- Key to fixed errors:
-- CENT : Center / Align Background Shape
-- LTS : Line Tip Issues
-- CST : Colored Shapes Touching
-- BS : BG Shape Size
-- RD : Redesign
-- AL : Alignment of lines/text

- adobe_capture : fixed stroke thickness, CENT
- adobe_connect : RD
- adobe_creative_cloud : CENT, minor other fixes
- adobe_fill_and_sign : no changes, just replaced MAIN with ALT
- adobe_illustrator_draw : RD
- adobe_lightroom : CENT, AL
- adobe_photoshop_express : CENT, fixed uneven sizes of squares, AL
- adobe_photoshop_sketch : RD
- adobe_spark_post : RD
- adobe_xd : CENT, AL
- asphalt_9 : RD of Background Shape
- behance : Spaced out the text a bit more
- bit_torrent : CENT, AL
- brawl_stars : CENT, LTS
- burger_king : RD
- camera_fv_5 : BS
- camera_mx : CST, LTS, CENT, AL
- canva : CENT
- chess_free : RD (although I would like to change BG, got any bright ideas ;P )
- crunchy_roll : CENT, AL
- dominos : CENT, AL, BS
- duolingo : RD
- edx : RD
- filmora_go : CENT, BS, AL, removed the "tail" :)
- five_hundred_px : rename, RD
- flipkart : CST, CENT, AL
- food_panda : RD
- gaana : BS, LTS, AL
- google_camera : RD
- ibis_paint_x : RD
- idm : CENT, AL
- idm_plus : CENT, AL, changes the "plus" from BG to stroke
- infinite_design : RD
- infinite_paint : RD
- inshorts : RD
- inshot : fixed the triangular holes / corners, CENT
- kinemaster : minor changes
- ludo_king : RD - decreased shapes and spikes (but I'd like to have your take on this one :)
- manual_camera_geekydevs : decluttered
- manual_camera_lensesdevs : increased breathing space, CENT, AL
- pay_tm : RD - PayPal happens to be the parent org of PayTM so designed the new icon after the PayPal logo from Appstract icon pack
- picsart : RD - simplified
- pubg : RD - simplified
- pubg_lite : RD - simplified
- rail_connect : decluttered, CENT, AL
- remini : fixed triangular holes
- starbucks : RD - simplified (Can you spot the coffee cup? ;)
- utorrent : LTS, CENT, AL
- upgrad : CENT, AL
- where_is_my_train : CENT, AL, fixed the windshield and circles
- wynk_music : RD - simplified
- youtube_go : RD
- zomato : AL and spacings

**Comment by The-King-Slayer** [comment]
Addition to change_log :

- Removed (/ merged where reqd. ) all previous ALT icons and added new ones

**Comment by mirrorkeydev** [comment]
Hi @The-King-Slayer!

adobe_capture : ✅

adobe_connect : ✅

adobe_creative_cloud : ✅

adobe_fill_and_sign : ✅

adobe_illustrator_draw : ✅

adobe_lightroom : ✅

adobe_photoshop_express : Black line square is still not a perfect square

adobe_photoshop_sketch : ✅

adobe_spark_post : ✅

adobe_xd : ✅

asphalt_9 : ✅ (this one looks especially cool, great job!)

behance : ✅

bit_torrent : ✅

brawl_stars : Sorry, but having no lines overlapping the background shape looks a little weird, I'd either add something to the middle or make the wings overlap

burger_king : Looking a lot better! However I would space the buns out even farther from the burger and remove the "curve" that hugs the burger, as the spacing is just too tight imo

camera_fv_5 : ✅

camera_mx : ✅

canva : ✅

chess_free : For the background here, I'd honestly just pick one of the colors and make it a square. I usually only use two colors when it's absolutely essential for the brand recognition (e.g. Burger King or Walmart)

crunchy_roll : ✅(although the black circles could be moved a little further from the center so the transparent gap between them and the background shape is a bit more defined)

dominos : ✅

duolingo : ✅ Love it!! Recognizable yet simple

edx : ✅

filmora_go : ✅

five_hundred_px : ✅

flipkart : CST, CENT, AL

food_panda : ✅

gaana : ✅

google_camera : Actually ended up changing the main camera design recently, but this works too! Can I ask why google camera gets its own camera icon?

ibis_paint_x : ✅

idm : LTS (bottom left of cloud and background shape)

idm_plus : LTS

infinite_design : ✅

infinite_paint : ✅ oo so smooth and flowy

inshorts : ✅

inshot : unfortunately by fixing the triangle holes it's still a LTS because the corners of the shape touch but don't cross the edges of the background shape

kinemaster : ✅

ludo_king : a lot better! the four colors can stay since it is central to the game, but they're just a little close to each other

manual_camera_geekydevs : ✅ love it, especially the little circle to the side

manual_camera_lensesdevs : ✅

pay_tm : ✅ smart, love the reference!

picsart : ✅so clean, love it

pubg : ✅great work

pubg_lite : ✅I assume this was modeled off of fb/fb lite? I think I want to start going away from the idea of switching stroke/background since it makes the background shape really small but if you're OK with it I'll let it go through for now and will add it to my own Todo list to fix later

rail_connect : ✅

remini : ✅

starbucks : Smart! I would just make the brown shape in the middle a little smaller so it has more breathing room from the green shape

utorrent : ✅

upgrad : ✅

where_is_my_train : ✅

wynk_music : ✅

youtube_go : ✅

zomato : ✅


As always, if you don't feel like making further adjustments (busy schedule, etc) I am happy to merge with only the approved icons :) 

Best,
Melanie

**Comment by The-King-Slayer** [comment]
Hi @mirrorkeydev ,

Sorry I got my eyes all messed up since a week, had an infection which just got worsened.
So I am running late on deadlines.

But anyway here is the patch update for revision-2:

adobe_photoshop_express : Fixed the black stroke square 
                                             (I'll be damned if I don't make it this time too, I got no idea who cursed this one -_-)

brawl_stars : stripped down all the cosmetics, and made THE minimalist icon. So, let me know what you think :)

burger_king : I am 100% agreed with your advice, did the necessary changes.

chess_free : Tried your version here, so let me know your views. I had an idea though - I agree we use single color for bg but how about we use different bg colors for light and dark icons ? E.g. Yellow for light and maroon for dark. Although this idea just popped up, but I think that's against the Appstract design ethos ?!

crunchy_roll : wish granted :P Moved the strokes a tiny bit to the right.

flipkart : same as brawl_stars, dropped the extras, essentials only :)

google_camera : no_changes - this app gets its own icon because unlike any other stock camera, google camera a.k.a. GCam can be installed in any phone like an app. E.g. you can't install an oppo or vivo camera in a xiaomi phone but you can do so with GCam.

idm : fixed LTS - although it shouldn't be there anymore still do let me know if the issue still persists

idm_plus : same as idm

inshot : my approach to solve this issue was to move the corners of the square inwards and extend the edges to cross over the shape.

ludo_king : adjusted the symmetrical distribution of the 4 color dots. Moved them away from each other.

pubg_lite : no changes for now - my take on the idea is actually I like the current approach, but still as an alternative, for the lite apps, we can keep the design same as the respective main icon, and just change the bg color to a lighter tint ? Or my second approach is a complete redesign of their own for lite apps (E.g. compare the main and alt pubg icons) . Anyway if you want to adapt this or any other style, let me know too, I'd be glad to see your solution and execute it :)

starbucks : great advice ! Now my little coffee cup looks even more pronounced. Love to see it.

Due to my infection, I am still recovering but I can see now at least, so being on leave, I currently have enough time in my hands to make the updates. So I am willing to at least make these icons perfect before I hit back at the office. Thus, if you got any other great ideas, please hit me up with a revision :D

Best Regards,
Aman

**Comment by mirrorkeydev** [comment]
Hi @The-King-Slayer!

adobe_photoshop_express : ✅

brawl_stars : ✅

burger_king : ✅

chess_free : ✅
`I had an idea though - I agree we use single color for bg but how about we use different bg colors for light and dark icons ? E.g. Yellow for light and maroon for dark.` -> I think it might become a little confusing tbh

crunchy_roll : ✅

flipkart : ✅

google_camera : `no_changes - this app gets its own icon because unlike any other stock camera, google camera a.k.a. GCam can be installed in any phone like an app. E.g. you can't install an oppo or vivo camera in a xiaomi phone but you can do so with GCam.` -> ah ok! I have a pixel phone, so it's the only camera on my phone, which is why i was confused ✅

idm : ✅

idm_plus : ✅

inshot : ✅

ludo_king : ✅

pubg_lite : `no changes for now` ✅ - `my take on the idea is actually I like the current approach, but still as an alternative, for the lite apps, we can keep the design same as the respective main icon, and just change the bg color to a lighter tint ? Or my second approach is a complete redesign of their own for lite apps (E.g. compare the main and alt pubg icons) . Anyway if you want to adapt this or any other style, let me know too, I'd be glad to see your solution and execute it :)` -> I like the 'lighter tint' idea!

starbucks : ✅

Great job! And sorry for being so late behind, everything looks great! If you want to make any more changes, you're welcome to do so now, (and make sure to delete the alt_icons folder and commit the deletion so it doesn't end up in the main branch), but otherwise we're good to merge!

**Comment by The-King-Slayer** [comment]
Hi @mirrorkeydev ,

I actually just wanted to modify the 2 lite apps viz. facebook_lite and pubg_lite to the lighter tint styles as discussed earlier but unfortunately my eyes are no good yet :( 

So, for now I have removed the ALT_icons folder so that this PR is good to be merged. I'll make a small patch update later for the lite icons, to-do list updated :)

Looking forward to the new Appstract update, cheers :D

**Comment by mirrorkeydev** [comment]
@The-King-Slayer

Thank you so much! Merging now 👍 

I'm so sorry about your eye infection, I hope it gets better soon and you have a restful time off from work :)

Best,
Melanie

**Pull request merged**
