### PR TITLE
Added Brainly, Game Space, Shopee from most requested icons list

### PR DESCRIPTION
**Pull request by ZeusOfTheCrows**
### Please read before accepting PR: 
* Is there an accepted standard for alternative icons? I want to add versions that I prefer, but I'm not sure are objectively better (e.g. my Zoom icon)
    - My Zoom/BlackPlayer icons have incorrect package names for this reason
* I have removed the completed commonly requested icons from the list - is that the correct thing to do?
* Would you prefer multiple small PRs (in case you have a script to accept them), or one bulk one?

I am happy for this PR to be denied so I can format it better, but I don't really want to add more icons until I know which is preferable

## Pull Request Checklist:

* [x] Have you added an explanation of which icons you've added and why you'd like us to include them?
* [x] Have you created three versions of each icon across the `svgs`, `appstract-light`, and `appstract-dark` folders?
* [x] Do all three icons have the same name, except for the file type ending? (For example, `app.svg`, `app.png`, and `app.png`)
* [x] Is each file name only comprised of lowercase letters, numbers, and underscores? Underscores should be used only to replace spaces. File names may not begin with a number.
    - Acceptable names: `hello.svg`, `bye_bye.svg`, `disney_plus.svg`, `numbers_123.svg`
    - Unacceptable names: `spaces everywhere.svg`, `YouTube.svg`, `$%*&^.svg`, `dots.between.svg`, `1something.svg`.
* [x] Have you ensured that all svgs and pngs are 192x192 px with a line width of 6px and a transparent background?
* [x] Did you add activity names for all of your icons to `app/xml/appfilter.xml`?
* [x] Did you add yourself to the `app/xml/contributors.xml` file? :)

## Icons added
Brainly (most requested)
Game Space (most requested)
Shopee (most requested)
Zoom Alt (Icon was in most requested)
Blackplayer Alt (Icon doesn't apply, or show in app)

### Template

For each icon added, please add an entry to the pull request (this text) formatted like this:

* App Name (`app_name.svg`) - [New/Redesigned] Icon
```
<item component="ComponentInfo{Activity Name 1}" drawable="app_name"/>
<item component="ComponentInfo{Activity Name 2}" drawable="app_name"/>
```
Brainly
```
<item component="ComponentInfo{co.brainly/com.brainly.StartActivity}" drawable="brainly"/>
```
Game Space
```
<item component="ComponentInfo{com.coloros.gamespaceui/com.coloros.gamespaceui.activity.StartActivity}" drawable="game_space"/>
<item component="ComponentInfo{com.oneplus.gamespace/com.oneplus.gamespace.ui.main.MainActivity}" drawable="game_space"/>
<item component="ComponentInfo{com.coloros.gamespace/com.coloros.gamespace.activity.GameBoxActivity}" drawable="game_space"/>
```
Shopee
```
<item component="ComponentInfo{com.shopee.br/com.shopee.app.ui.home.HomeActivity_}" drawable="shopee"/>
<item component="ComponentInfo{com.shopee.ph/com.shopee.app.ui.home.HomeActivity_}" drawable="shopee"/>
<item component="ComponentInfo{com.shopee.id/com.shopee.app.ui.home.HomeActivity_}" drawable="shopee"/>
<item component="ComponentInfo{com.shopee.th/com.shopee.app.ui.home.HomeActivity_}" drawable="shopee"/>
```
Zoom alt
```
<item component="ComponentInfo{alternative.us.zoom.videomeetings/com.zipow.videobox.alternative.LauncherActivity}" drawable="zoom_alt"/>
```
Blackplayer alt
```
<item component="ComponentInfo{alternative.com.kodarkooperativet.blackplayer/com.kodarkooperativet.blackplayer.activities.ViewPagerActivity}" drawable="blackplayer_alt"/>
<item component="ComponentInfo{alternative.com.kodarkooperativet.blackplayerex/com.kodarkooperativet.blackplayerex.activities.ViewPagerActivity}" drawable="blackplayer_alt"/>
<item component="ComponentInfo{alternative.com.kodarkooperativet.blackplayerfree/com.kodarkooperativet.blackplayerfree.activities.ViewPagerActivity}" drawable="blackplayer_alt"/>
```

### CODE REVIEW

**Comment by mirrorkeydev** [comment]
Hey @ZeusOfTheCrows!

To your PR questions:

- I don't currently have a standard for alternative icons. There's also the distinction between `alternative icons` = proposing multiple in the PR and then having me decide which one to use -- vs. -- `alternative icons` = adding a new second icon for an app to coexist with the main one (which I have only started doing as of the last update). I think you mean the second one, but there has been some discussion about the first one in the past (see #24). Right now I'm just handling it on a case-by-case basis - for example, I have no problem with you just replacing the zoom icon with the one you created (I personally like it better than the one I made, although I would exaggerate the top-right/bottom-left rounding of the corners a bit more or else it won't be noticeable on small screens). If you do want the other zoom icon to stay, what ends up happening is that no new entry for the alternative icon gets added to `appfilter.xml`. Instead, it's just included in the app assets and `drawable.xml` (autogenerated, don't worry about adding it manually), and then users would have to manually apply it to the app of their choice. So, in a sense, one icon becomes the primary auto-applied icon, and the other one is an opt-in alternative. Also, I don't think BlackPlayer currently has an icon? At least, I couldn't find one, so yours would be the primary one (`appfilter.xml` may have an entry, but that doesn't strictly mean that the icon exists -- only if `drawable.xml` has an entry).
- Yes, this is fine! (preferred, actually, I should add a note about that to the contributing guide)
- Bulk PRs are fine, although I prefer smaller ones spaced out over time, especially if you want feedback regarding your icon designs. Generally I give people the option to either address feedback in their PR for icons that I'm not comfortable merging as-is, or if that's too much trouble, just removing the icons in question from the PR and merging the other ones. I took a look at your icons though and they all look great, so I wouldn't worry about a lengthy review process or bulk PRs in your case :) This repository mostly just behaves as a stockpile of new icons and updates to the key xml files, and I bundle them into the app during releases manually, so don't worry about triggering any deploy scripts.

Please let me know if you have any more questions, I'm happy to answer them! :)

**Comment by ZeusOfTheCrows** [comment]
Thank you for your response, I've made the following changes

* You were correct, that was what I was referring to. 
  - I agree with you about the zoom icon, I've changed that
  - I've renamed the zoom and blackplayer icons from _alt, I'll let you rename your own (as it's already been designed, it may as well stay in the app?)
* Cool, I'll continue doing that
* If you prefer small ones, I'll do a new one every ~10 icons?

**Comment by ZeusOfTheCrows** [comment]
Ah, I forgot pull requests aren't static - here are the total added icons:


aptoide
```
<item component="ComponentInfo{cm.aptoide.pt/cm.aptoide.pt.view.MainActivity}" drawable="aptoide"/>
```

blackplayer
```
<item component="ComponentInfo{com.kodarkooperativet.blackplayer/com.kodarkooperativet.blackplayer.activities.ViewPagerActivity}" drawable="blackplayer"/>
<item component="ComponentInfo{com.kodarkooperativet.blackplayerex/com.kodarkooperativet.blackplayerex.activities.ViewPagerActivity}" drawable="blackplayer"/>
<item component="ComponentInfo{com.kodarkooperativet.blackplayerfree/com.kodarkooperativet.blackplayerfree.activities.ViewPagerActivity}" drawable="blackplayer"/>
```

brainly
```
<item component="ComponentInfo{co.brainly/com.brainly.StartActivity}" drawable="brainly"/>
```

bromite
```
<item component="ComponentInfo{org.bromite.bromite/com.google.android.apps.chrome.Main}" drawable="bromite"/>
```

capcut
```
<item component="ComponentInfo{com.lemon.lvoverseas/com.vega.launcher.precondition.PreInstallConfirmActivity}" drawable="capcut"/>
```

firefox beta
```
<item component="ComponentInfo{org.mozilla.firefox_beta/org.mozilla.firefox_beta.App}" drawable="firefox_beta" />
```

flo
```
<item component="ComponentInfo{org.iggymedia.periodtracker/org.iggymedia.periodtracker.activities.InitialActivity}" drawable="flo"/>
```

game space
```
<item component="ComponentInfo{com.coloros.gamespaceui/com.coloros.gamespaceui.activity.StartActivity}" drawable="game_space"/>
<item component="ComponentInfo{com.oneplus.gamespace/com.oneplus.gamespace.ui.main.MainActivity}" drawable="game_space"/>
<item component="ComponentInfo{com.coloros.gamespace/com.coloros.gamespace.activity.GameBoxActivity}" drawable="game_space"/>
```

google go
```
<item component="ComponentInfo{com.google.android.apps.searchlite/com.google.android.apps.searchlite.ui.SearchActivity}" drawable="google_go"/>
```

infinity for reddit
```
<item component="ComponentInfo{ml.docilealligator.infinityforreddit/ml.docilealligator.infinityforreddit.activities.MainActivity}" drawable="infinity_for_reddit"/>
```

klck (kustom)
```
<item component="ComponentInfo{org.kustom.lockscreen/org.kustom.app.OnBoardingActivity}" drawable="kustom_klck"/>
```

klwp (kustom)
```
<item component="ComponentInfo{org.kustom.wallpaper/org.kustom.app.OnBoardingActivity}" drawable="kustom_klwp"/>
<item component="ComponentInfo{org.kustom.wallpaper/org.kustom.lib.editor.WpAdvancedEditorActivity}" drawable="kustom_klwp"/>
<item component="ComponentInfo{org.kustom.wallpaper/org.kustom.lib.settings.SettingsActivity}" drawable="kustom_klwp"/>
<item component="ComponentInfo{org.kustom.wallpaper/org.kustom.lib.settings.WpSettingsActivity}" drawable="kustom_klwp"/>
```

kwgt (kustom)
```
<item component="ComponentInfo{org.kustom.widget.pro/a.y.z.HZ}" drawable="kustom_kwgt"/>
<item component="ComponentInfo{org.kustom.widget.pro/org.kustom.pro.MainActivity}" drawable="kustom_kwgt"/>
<item component="ComponentInfo{org.kustom.widget/org.kustom.widget.picker.WidgetPicker}" drawable="kustom_kwgt"/>
```

last.fm (+ simple scrobbler)
```
<item component="ComponentInfo{fm.last.android/fm.last.android.ui.activity.SplashScreen}" drawable="last_fm"/>
<item component="ComponentInfo{com.adam.aslfms/com.adam.aslfms.SettingsActivity}" drawable="last_fm"/>
```

shopee
```
<item component="ComponentInfo{com.shopee.br/com.shopee.app.ui.home.HomeActivity_}" drawable="shopee"/>
<item component="ComponentInfo{com.shopee.ph/com.shopee.app.ui.home.HomeActivity_}" drawable="shopee"/>
<item component="ComponentInfo{com.shopee.id/com.shopee.app.ui.home.HomeActivity_}" drawable="shopee"/>
<item component="ComponentInfo{com.shopee.th/com.shopee.app.ui.home.HomeActivity_}" drawable="shopee"/>
```

soundhound
```
<item component="ComponentInfo{com.melodis.midomiMusicIdentifier.freemium/com.soundhound.android.appcommon.activity.SplashScreenActivity}" drawable="soundhound"/>
```

zoom
```
<item component="ComponentInfo{us.zoom.videomeetings/com.zipow.videobox.LauncherActivity}" drawable="zoom"/>
```

**Comment by mirrorkeydev** [comment]
Beautiful, thanks for your contribution!

**Pull request merged**
