### PR TITLE
20 new icons + 1 redesigned

### PR DESCRIPTION
**Pull request by shutupayouface**
icons i'm submitting for approval: AllTrails, AMEX ,  Asana, Basecamp , Bigcommerce, BofA, CBS,  ESPN , Kickstarter, Live Soccer TV, Opentable, Strong, Tidio, The Athletic, Youtube TV 

icons redesigned and submitted for your consideration: 1Password

* AllTrails (`alltrails.svg`) - New Icon
```
<item component="ComponentInfo{com.alltrails.alltrails/com.alltrails.alltrails.StartActivity}" drawable="all__trails" />
```

* AMEX (`amex_mobile.svg`) - New Icon
```
<item component="ComponentInfo{com.americanexpress.android.acctsvcs.us/com.americanexpress.android.acctsvcs.us.firstuse.StartupActivity}" drawable="amex_mobile" />
```

* Asana (`asana.svg`) - New Icon
```
<item component="ComponentInfo{com.asana.app/com.asana.ui.activities.LaunchActivity}" drawable="asana" />
```

* Basecamp (`basecamp.svg`) - New Icon
```
<item component="ComponentInfo{com.basecamp.bc3/com.basecamp.bc3.activities.HomeActivity}" drawable="basecamp" />
```
 
* Bigcommerce (`bigcommerce.svg`) - New Icon
```
<item component="ComponentInfo{com.bigcommerce.mobile/com.bigcommerce.heartbeat.ui.launch.LaunchActivity}" drawable="bigcommerce" />
```

* BofA (`bank_of_america.svg`) - New Icon
```
<item component="ComponentInfo{com.infonow.bofa/com.infonow.bofa.Launcher}" drawable="bank_of_america" />
```

* CBS (`cbs.svg`) - New Icon
```
<item component="ComponentInfo{com.cbs.app/com.cbs.app.view.SplashActivity}" drawable="cbs" />
<item component="ComponentInfo{com.cbs.app/com.cbs.app.screens.startup.SplashActivity}" drawable="cbs" />
```

* ESPN (`espn.svg`) - New Icon
```
<item component="ComponentInfo{air.WatchESPN/com.espn.watchespn.main.Main}" drawable="espn" />
<item component="com.espn.score_center/com.espn.sportscenter.ui.EspnLaunchActivity}" drawable="espn" />
```

* Kickstarter (`kickstarter.svg`) - New Icon
```
<item component="ComponentInfo{com.kickstarter.kickstarter/com.kickstarter.ui.activities.DiscoveryActivity}" drawable="kickstarter" />
```

* Live Soccer TV (`live_soccer_tv.svg`) - New Icon
```
<item component="ComponentInfo{com.livesoccertv/com.livesoccertv.RootActivity}" drawable="live_soccer_tv" />
```

* Opentable (`opentable.svg`) - New Icon
```
<item component="ComponentInfo{com.opentable/com.opentable.activities.search.SearchResults}" drawable="opentable" />
```

* Strong (`strong.svg`) - New Icon
```
<item component="ComponentInfo{io.strongapp.strong/io.strongapp.strong.MainActivity}" drawable="strong" />
```

* Tidio (`tidio.svg`) - New Icon
```
<item component="ComponentInfo{com.tidiochat.app/com.tidiochat.app.activity.MainActivity}" drawable="tidio"/>
<item component="ComponentInfo{com.tidiochat.app/com.tidiochat.app.SplashActivity}" drawable="tidio"/>
```

* The Athletic (`the_athletic.svg`) - New Icon
```
<item component="ComponentInfo{com.theathletic/com.theathletic.activity.SplashActivity}" drawable="the_athletic"/>
```

* Youtube TV (`youtube_tv.svg`) - New Icon
```
<item component="ComponentInfo{com.google.android.apps.youtube.unplugged/com.google.android.apps.youtube.unplugged.features.main.MainActivity}" drawable="youtube_tv" />
```

* 1password (`one_password.svg`) - Redesigned Icon
```
<item component="ComponentInfo{com.agilebits.onepassword/com.agilebits.onepassword.activity.LoginActivity}" drawable="one_password"/>
```

### CODE REVIEW

**Comment by mirrorkeydev** [comment]
Hello @shutupayouface!

Thank you for your contribution to Appstract!

Some formatting stuff: it looks like some of the activity names that you added to `appfilter.xml` already existed - I only searched `asana` but it's likely that others already existed too, since a lot of the icons you're contributing are of very well-known apps.

From the contribution guide:
> Important: before you add a new activity name to appfilter.xml, do a ctrl-f and search for your icon - it's possible that a section for your icon already exists. If that's the case, just modify that section to match your icon file name and add any new activity names not already in that section. If you don't check for existing sections before adding a new one, your icons might not apply correctly.

As for your icons, they look great! My favorites are basecamp, espn, kickstarter, and tidio -- they're all super clean, minimalist, and will fit in seamlessly.

For some of the other icons, I'll separate my comments into two sections: `highly prefer that you address this` and `up to you if you want to address this`

#### Up to you if you want to address this
- For `bank_of_america` I think you did a brilliant job of evoking the original icon! If I could request one thing, it would be to slightly increase size of the gaps between the colored blobs - when the icons are viewed at a really small size on phones, the gap will look really small.

#### Highly prefer that you address this
image
- `live_soccer_tv`: For me, the amount of "colored blob" is just too low - the lines on a completely transparent background will get lost really easily. I think there's a lot of ways you could fix this though -- one thing that sticks out to me is that the original icon has a red soccer ball:
image
So maybe you could do something like this? I widened the blob at the bottom and added in the red. Just an idea though, feel free to do something completely different if you like!
image
(.svg [here](https://github.com/mirrorkeydev/mirrorkeydev/blob/master/live_soccer_tv.svg))
- `strong`: I realize that a barbell is a difficult image to make look like the Appstract design ethos, but there's no overlap of the lines onto the colored blobs (from the contribution guide: 
image)
The blobs are also a little small but if you make them bigger it'd be hard for it to be recognizable, so up to you if you want to find a way to address that :) It's mostly the line thing that's an issue

**Comment by shutupayouface** [comment]
thank you for reviewing my contribution!  i'm sorry about `asana` — i did search the list, but i must have done something wrong to miss it.

i will fix `bank_of_america` and `strong` based on your comments.  as for `live_soccer_tv` i think your interpretation is perfect and i wouldn't change anything.

**Comment by mirrorkeydev** [comment]
Heads up, one of your new filenames doesn't conform with the naming convention, which is why the check is [failing](https://github.com/mirrorkeydev/Appstract/pull/13/checks?check_run_id=1508522770). I'm not sure why the check didn't run on any of the previous commits you pushed, only once I merged the master branch into your branch? Maybe it doesn't like merge conflicts haha

It looks like it's `disney+` that it's unhappy with; from the [pull request template](https://github.com/mirrorkeydev/Appstract/blob/master/PULL_REQUEST_TEMPLATE.md):
>  Is each file name only comprised of lowercase letters, numbers, and underscores? Underscores should be used only to replace spaces. File names may not begin with a number. Acceptable names: hello.svg, bye_bye.svg, disney_plus.svg, numbers_123.svg Unacceptable names: spaces everywhere.svg, YouTube.svg, $%*&^.svg, dots.between.svg, 1something.svg.

**Comment by shutupayouface** [comment]
> It looks like it's `disney+` that it's unhappy with

i thought that looked wrong, but that was the name in the "most requested icons" file, so i left it that way.  i'll fix it.

thank you for all your comments & help!

**Comment by mirrorkeydev** [comment]
Feel free to request a review from me (top right of the PR), when you're ready for me to look at this PR again (so I don't jump the gun and review in-progress work, or if you're planning on adding more icons) :)

**Comment by shutupayouface** [comment]
> Feel free to request a review from me (top right of the PR), when you're ready for me to look at this PR again (so I don't jump the gun and review in-progress work, or if you're planning on adding more icons) :)

i am done, but there isn't anyone listed under "Reviewers" to request a review from.  all of the sections in the sidebar are empty.  sorry if i've done something incorrectly.

**Comment by mirrorkeydev** [comment]
Oh no worries! You haven't done anything wrong, I had to google it: you have to be an invited collaborator on a repository to formally request review (so my bad for asking that haha). I'll take a look at everything now! :)

**Comment by mirrorkeydev** [comment]
Everything looks good, except the `live_soccer_tv` icon hasn't been updated :) [Source svg here.](https://github.com/mirrorkeydev/mirrorkeydev/blob/master/live_soccer_tv.svg) After that, we should be good to merge!

**Comment by shutupayouface** [comment]
> Everything looks good, except the `live_soccer_tv` icon hasn't been updated :) [Source svg here.](https://github.com/mirrorkeydev/mirrorkeydev/blob/master/live_soccer_tv.svg) After that, we should be good to merge!

updated!  all set now—thanks.

**Comment by kaugummiheld** [comment]
Hey @shutupayouface, 

first of all let me say thank you for contributing. 
I'm in love with your interpretation of the Niagara, Sesame and Bank of America. They all look really clean and neat! :) 

I have two point which I want to mention: 

First of all, there is already an icon for **1password** in the recent PlayStore version. I'm sure you're probably unaware but not all original icons of Appstract are currently on Github. This was basically a safety measure of @mirrorkeydev since she didn't want to have her work stolen which I'm totally getting. - Anyways, the original version and yours aren't that different, but I have to say I prefer the simpler version of @mirrorkeydev. :neutral_face: 

Secondly, there are some app icons which feel a little bit off to me. If you don't mind, I'd say something to those: 
* For `opentable.svg` I get where you're coming from. I have the same workflow of starting with the original app icon and simplify it as much as possible. The "problem" here (at least for me) is that the original icon is already pretty simple, but doesn't fit the ethos of Appstract, e.g. at least a single black line which for me is one of our trademarks is missing. I did some drafts and came up with these two versions. I'd like to hear what you think about them: 
opentable
* I'm all for the changing of your `strong.svg` icon to leave some space between the lines and colored forms. That's great! I was thinking why use multiple lines in the beginning? Could this be a more Appstract-like version of it. Your thoughts?
strong
 * The last one is `the_athletic.svg`. While I really like your idea, something is bothering me. I don't really get my fingers on what exactly. Maybe the A is still to many details. What I definitely noticed is an inconsistency in your black line endings (see #15).
the_athletic
I'm also no big fan of my versions, but maybe we can come up with something?
the_athletic

At the end, let me make it clear again: I'm not here to insult you or the amount of work you've done. I appreciate all of it and am happy to see that others also enjoy making icons. - I just want to preserve the Appstract ethos, since I'm loving it. :)

**Comment by shutupayouface** [comment]
> First of all, there is already an icon for **1password** in the recent PlayStore version. I'm sure you're probably unaware but not all original icons of Appstract are currently on Github. This was basically a safety measure of @mirrorkeydev since she didn't want to have her work stolen which I'm totally getting. - Anyways, the original version and yours aren't that different, but I have to say I prefer the simpler version of @mirrorkeydev. 😐

that is fine with me, i submitted it as an option for consideration. i don't plan to recreate existing icons much in the future.

> Secondly, there are some app icons which feel a little bit off to me. If you don't mind, I'd say something to those:
> 
> * For `opentable.svg` I get where you're coming from. I have the same workflow of starting with the original app icon and simplify it as much as possible. The "problem" here (at least for me) is that the original icon is already pretty simple, but doesn't fit the ethos of Appstract, e.g. at least a single black line which for me is one of our trademarks is missing. I did some drafts and came up with these two versions. I'd like to hear what you think about them:
>   opentable

i think the second `opentable.svg` icon works quite well and i'd be happy if that one is used.

> * I'm all for the changing of your `strong.svg` icon to leave some space between the lines and colored forms. That's great! I was thinking why use multiple lines in the beginning? Could this be a more Appstract-like version of it. Your thoughts?
>   strong

i think this version with the full bar on top works well, too.  i think it just needs the rounded caps, as you reference below.

> * The last one is `the_athletic.svg`. While I really like your idea, something is bothering me. I don't really get my fingers on what exactly. Maybe the A is still to many details. What I definitely noticed is an inconsistency in your black line endings (see #15).
>   the_athletic
>   I'm also no big fan of my versions, but maybe we can come up with something?
>   the_athletic

i quite like both of your interpretations here. so please feel free to choose one over mine.

> At the end, let me make it clear again: I'm not here to insult you or the amount of work you've done. I appreciate all of it and am happy to see that others also enjoy making icons. - I just want to preserve the Appstract ethos, since I'm loving it. :)

i totally understand.  my hope is contribute some of the most requested icons while also adding some icons for the apps that i use.  no offense will be taken if my interpretations don't work or need updating.

as for the 3 icons above, will you update these?  or should i do it?  thanks.

**Comment by kaugummiheld** [comment]
Thank you for your understanding and support. 

> as for the 3 icons above, will you update these? or should i do it? thanks.
I'll take care of it! At least the first two. Have to think a little bit more about the last one. :)

**Comment by shutupayouface** [comment]
> Thank you for your understanding and support.
> 
> > as for the 3 icons above, will you update these? or should i do it? thanks.
> > I'll take care of it! At least the first two. Have to think a little bit more about the last one. :)

thanks 👍

**Pull request merged**
