### PR TITLE
Add adaway, galaxy themes, lazada, solid explorer, some generic icons; modified foodpanda, opentable

### PR DESCRIPTION
**Pull request by ZeusOfTheCrows**
Some more icons! I changed the OpenTable icon to a stroke rather than a dark blob, which I thought fitted better, and I changed the foodpanda icon to pure black (which it wasn't); I added some generic icons for euro and gbp; and I also converted all the whitespace in contributors.xml to tabs, as it was a mix.

## Pull Request Checklist:

* [x] Have you added an explanation of which icons you've added and why you'd like us to include them?
* [x] Have you created three versions of each icon across the `svgs`, `appstract-light`, and `appstract-dark` folders?
* [x] Do all three icons have the same name, except for the file type ending? (For example, `app.svg`, `app.png`, and `app.png`)
* [x] Is each file name only comprised of lowercase letters, numbers, and underscores? Underscores should be used only to replace spaces. File names may not begin with a number.
    - Acceptable names: `hello.svg`, `bye_bye.svg`, `disney_plus.svg`, `numbers_123.svg`
    - Unacceptable names: `spaces everywhere.svg`, `YouTube.svg`, `$%*&^.svg`, `dots.between.svg`, `1something.svg`.
* [x] Have you ensured that all svgs and pngs are 192x192 px with a line width of 6px and a transparent background?
* [x] Did you add activity names for all of your icons to `app/xml/appfilter.xml`?
* [x] Did you add yourself to the `app/xml/contributors.xml` file? :)

## Icons added

* FoodPanda - Redesigned icon
```
<item component="ComponentInfo{com.global.foodpanda.android/de.foodora.android.ui.launcher.LauncherActivity}" drawable="food_panda" />
<item component="ComponentInfo{com.global.foodpanda.android/com.global.foodpanda.android.activities.SplashScreenActivity}" drawable="food_panda" />
<item component="ComponentInfo{com.india.foodpanda.android/com.india.foodpanda.android.welcome.activities.SplashScreenActivity}" drawable="food_panda" />
```

* opentable - redesigned icon
```
<item component="ComponentInfo{com.opentable/com.opentable.activities.search.SearchResults}" drawable="opentable" />
```

==============================================================================

* adaway - new icon
```
<item component="ComponentInfo{org.adaway/org.adaway.ui.home.HomeActivity}" drawable="adaway"/>
<item component="ComponentInfo{org.adaway/org.adaway.ui.BaseActivity}" drawable="adaway" />
```

* galaxy themes (+ alt version) - new icon
```
<item component="ComponentInfo{com.samsung.android.themestore/com.samsung.android.themestore.activity.Launcher}" drawable="galaxy_themes"/>
```

* lazada - new icon
```
<item component="ComponentInfo{com.lazada.android/com.lazada.activities.EnterActivity}" drawable="lazada"/>
```

* solid explorer - new icon
```
<item component="ComponentInfo{pl.solidexplorer/pl.solidexplorer.SolidExplorer}" drawable="solid_explorer" />
<item component="ComponentInfo{pl.solidexplorer1/pl.solidexplorer.SolidExplorer}" drawable="solid_explorer" />
<item component="ComponentInfo{pl.solidexplorer2/pl.solidexplorer.SolidExplorer}" drawable="solid_explorer" />
```

* generic bank EU / generic bank UK - new icon 
```
[no package name]
```
* generic wifi, cell, and battery icons - new icon
```
[no package name]
```

### CODE REVIEW

**Comment by mirrorkeydev** [comment]
Hi @ZeusOfTheCrows!

Sorry for the delay, I'm dealing with a lot of schoolwork and work. I'll have this reviewed by the weekend :)

**Comment by ZeusOfTheCrows** [comment]
Dont worry about it, no rush! The reason I'm sending them quickly is because I know I've only got so long before I go off a project, so I'm doing a bunch before that point (I've actually got a few more, but I didn't want to overload you)

**Comment by mirrorkeydev** [comment]
Hi @ZeusOfTheCrows!

The icons look wonderful! The only change I'd like to request is that it looks like the strokes are too thin on `solid_explorer` (Inkscape said they were at 4.44px instead of 6px).

Just curious, what was the modification on food panda? I see that you only touched the `appstract_light` version

> The reason I'm sending them quickly is because I know I've only got so long before I go off a project, so I'm doing a bunch before that point (I've actually got a few more, but I didn't want to overload you)

Ah, gotcha. Sounds good!

**Comment by mirrorkeydev** [comment]
Looks good!

**Pull request merged**
