### PR TITLE
Added icons

### PR DESCRIPTION
**Pull request by CreepyCat225**
## Pull Request Checklist:

* [x] Have you added an explanation of which icons you've added and why you'd like us to include them?
* [x] Have you created three versions of each icon across the `svgs`, `appstract-light`, and `appstract-dark` folders?
* [x] Do all three icons have the same name, except for the file type ending? (For example, `app.svg`, `app.png`, and `app.png`)
* [x] Is each file name only comprised of lowercase letters, numbers, and underscores? Underscores should be used only to replace spaces.
    - Acceptable names: `hello.svg`, `bye_bye.svg`, `disney_plus.svg`, `numbers_123.svg`
    - Unacceptable names: `spaces everywhere.svg`, `YouTube.svg`, `$%*&^.svg`
* [x] Have you ensured that all svgs and pngs are 192x192 px with a line width of 6px and a transparent background?

## Icons added
ADM (advanced download manager)
Xbox app
Mobily

* ADM (`adm.svg`) - New Icon
```
<item component="ComponentInfo{com.dv.adm/com.dv.get.Main}" drawable="adm"/>
```
* Xbox (`xbox.svg`) - New Icon
```
<item component="ComponentInfo{com.microsoft.xle/com.microsoft.xbox.xle.app.XLEActivity}" drawable="xbox"/>
<item component="ComponentInfo{com.microsoft.smartglass/com.microsoft.xbox.xle.app.XLEActivity}" drawable="xbox"/>
<item component="ComponentInfo{com.microsoft.xboxone.smartglass/com.microsoft.xbox.MainActivity}" drawable="xbox"/>
```
* Mobily (`mobily.svg`) - New Icon
```
<item component="ComponentInfo{com.mobily.activity/com.mobily.activity.core.navigation.RouteActivity}" drawable="mobily"/>
```

### CODE REVIEW

**Comment by mirrorkeydev** [comment]
Hello @CreepyCat225!

Congratulations on being the first person to test out the contribution process for Appstract! I hope that it went smoothly for you, I'm still working on refining some of the steps.

Your icons look really nice! My favorite is the Mobily icon, it's really on theme :)

My only requested changes are:
- You have a some changes in this PR unrelated to the root work that you did, such as deleting some of the other files; not sure if this was intended or not
image
This should be fixable by following the top answer [here](https://stackoverflow.com/questions/12481639/remove-files-from-git-commit). In summary:
```bash
git reset --soft HEAD^ 
git reset HEAD path/to/unwanted_file # do this for each file you didn't mean to add/edit/delete
git commit -c ORIG_HEAD 
git push origin master -f
````
- For the ADM icon, would you mind making it so the colored blobs don't touch? I know that wasn't clear in the contribution/style guide -- I'll make sure to add a new section ASAP that clarifies that it's part of the design ethos.
- I do already have an Xbox icon, I guess it wasn't applying for all because I was missing the correct activity name, sorry about that! I'll definitely add all of the activity names you mentioned. My icon is below, feel free to make a case as to why you'd like your icon to replace it if you'd like. I think in the future I will add all of my icons to the repository, so that this doesn't happen again :/ I'm really sorry me not adding all my icons caused you to do potentially unnecessary work.
image

I'm so excited to have your contributions! Please let me know if any of these requests are prohibitive.

**Comment by CreepyCat225** [comment]
Hi, @mirrorkeydev 

Sorry for the late response as I created the pull request late at night

I have some questions:
A ) Do you want the .svg versions of my icons or not? In other words, do you want me to put back the svg icons that came with the project? 
Ok, i've done just that, removed my svgs, and added back yours, is that what you wanted?
sorry if i am doing something wrong here but i don't usually use github (:

B ) I have fixed the ADM icon, is it good now or does it need some more tweaking?

C ) Yeah I was pretty sure I have seen that icon somewhere but when I looked at the icon i had, it wasn't changed, that's totally my bad since I should have checked through the app

**Comment by mirrorkeydev** [comment]
Hey @CreepyCat225!

No worries at all :) To your questions:

A) Sorry, I should have been a little clearer: I wanted your svgs in addition to the svgs that were already in the folder, not for them to replace each other. I've added a commit that does that, so no worries about doing that! GitHub can be a little tricky, I'll try to add more guidance in the contribution guide to help others in the future :)

B) Yes, it looks great! Full disclosure, I did edit it (and Mobily) a little to add more breathing room around the edges (something else I forgot to add to the contribution guide - this has been a great reminder!)

This PR looks good to merge for me!

**Comment by CreepyCat225** [comment]
Yeah, it confused me a little bit but No problem at all, I also was kind of wandering about some padding when I was making them but the guide mentioned none of that. nonetheless, I am glad I could help in any way.

Thrilled to seeing my icons in the app, and Looking forward to contributing more in the near future, although I seriously need to step up my design game😅.

**Comment by mirrorkeydev** [comment]
Merged! I'm glad to have your contribution!

Oh one more thing! I'll add this the pull request template in the future, but for now I'm manually adding contributors to the file.

```
    <contributor
        name="Name 1"
        contribution="Contribution 1, contribution 2"
        image="https://avatars1.githubusercontent.com/u/23138905?v=3&amp;s=300"
        link="" />
```

What do you want me to fill out for you? Feel free to use your GitHub username as your name, or only your first name and last initial - whatever you're comfortable with. I was thinking the link would point to your GitHub, but if you have a different social media (twitter, blog, etc) that you'd rather link, feel free to mention that as well.

**Comment by CreepyCat225** [comment]
Nice!!

```
<contributor
        name="CreepyCat225"
        contribution="ADM, Mobily"
        image="https://avatars2.githubusercontent.com/u/66734989?s=400&u=d40aaa0ae58a7a9b99ff29f8f82c5c5a5df0c49e&v=4"
        link="https://github.com/CreepyCat225" />
```

**Pull request merged**
